// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: backend/v1/actions.proto

package backend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrchestratorAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SequenceNumber uint64                 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventHash      []byte                 `protobuf:"bytes,3,opt,name=event_hash,json=eventHash,proto3" json:"event_hash,omitempty"`
	// Types that are assignable to OrchestratorActionType:
	//
	//	*OrchestratorAction_ScheduleTask
	//	*OrchestratorAction_CreateSubOrchestration
	//	*OrchestratorAction_CreateTimer
	//	*OrchestratorAction_SendEvent
	//	*OrchestratorAction_CompleteOrchestration
	//	*OrchestratorAction_TerminateOrchestration
	OrchestratorActionType isOrchestratorAction_OrchestratorActionType `protobuf_oneof:"orchestrator_action_type"`
}

func (x *OrchestratorAction) Reset() {
	*x = OrchestratorAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_v1_actions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestratorAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorAction) ProtoMessage() {}

func (x *OrchestratorAction) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_actions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorAction.ProtoReflect.Descriptor instead.
func (*OrchestratorAction) Descriptor() ([]byte, []int) {
	return file_backend_v1_actions_proto_rawDescGZIP(), []int{0}
}

func (x *OrchestratorAction) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *OrchestratorAction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *OrchestratorAction) GetEventHash() []byte {
	if x != nil {
		return x.EventHash
	}
	return nil
}

func (m *OrchestratorAction) GetOrchestratorActionType() isOrchestratorAction_OrchestratorActionType {
	if m != nil {
		return m.OrchestratorActionType
	}
	return nil
}

func (x *OrchestratorAction) GetScheduleTask() *ScheduleTaskAction {
	if x, ok := x.GetOrchestratorActionType().(*OrchestratorAction_ScheduleTask); ok {
		return x.ScheduleTask
	}
	return nil
}

func (x *OrchestratorAction) GetCreateSubOrchestration() *CreateSubOrchestrationAction {
	if x, ok := x.GetOrchestratorActionType().(*OrchestratorAction_CreateSubOrchestration); ok {
		return x.CreateSubOrchestration
	}
	return nil
}

func (x *OrchestratorAction) GetCreateTimer() *CreateTimerAction {
	if x, ok := x.GetOrchestratorActionType().(*OrchestratorAction_CreateTimer); ok {
		return x.CreateTimer
	}
	return nil
}

func (x *OrchestratorAction) GetSendEvent() *SendEventAction {
	if x, ok := x.GetOrchestratorActionType().(*OrchestratorAction_SendEvent); ok {
		return x.SendEvent
	}
	return nil
}

func (x *OrchestratorAction) GetCompleteOrchestration() *CompleteOrchestrationAction {
	if x, ok := x.GetOrchestratorActionType().(*OrchestratorAction_CompleteOrchestration); ok {
		return x.CompleteOrchestration
	}
	return nil
}

func (x *OrchestratorAction) GetTerminateOrchestration() *TerminateOrchestrationAction {
	if x, ok := x.GetOrchestratorActionType().(*OrchestratorAction_TerminateOrchestration); ok {
		return x.TerminateOrchestration
	}
	return nil
}

type isOrchestratorAction_OrchestratorActionType interface {
	isOrchestratorAction_OrchestratorActionType()
}

type OrchestratorAction_ScheduleTask struct {
	ScheduleTask *ScheduleTaskAction `protobuf:"bytes,10,opt,name=schedule_task,json=scheduleTask,proto3,oneof"`
}

type OrchestratorAction_CreateSubOrchestration struct {
	CreateSubOrchestration *CreateSubOrchestrationAction `protobuf:"bytes,11,opt,name=create_sub_orchestration,json=createSubOrchestration,proto3,oneof"`
}

type OrchestratorAction_CreateTimer struct {
	CreateTimer *CreateTimerAction `protobuf:"bytes,12,opt,name=create_timer,json=createTimer,proto3,oneof"`
}

type OrchestratorAction_SendEvent struct {
	SendEvent *SendEventAction `protobuf:"bytes,13,opt,name=send_event,json=sendEvent,proto3,oneof"`
}

type OrchestratorAction_CompleteOrchestration struct {
	CompleteOrchestration *CompleteOrchestrationAction `protobuf:"bytes,14,opt,name=complete_orchestration,json=completeOrchestration,proto3,oneof"`
}

type OrchestratorAction_TerminateOrchestration struct {
	TerminateOrchestration *TerminateOrchestrationAction `protobuf:"bytes,15,opt,name=terminate_orchestration,json=terminateOrchestration,proto3,oneof"`
}

func (*OrchestratorAction_ScheduleTask) isOrchestratorAction_OrchestratorActionType() {}

func (*OrchestratorAction_CreateSubOrchestration) isOrchestratorAction_OrchestratorActionType() {}

func (*OrchestratorAction_CreateTimer) isOrchestratorAction_OrchestratorActionType() {}

func (*OrchestratorAction_SendEvent) isOrchestratorAction_OrchestratorActionType() {}

func (*OrchestratorAction_CompleteOrchestration) isOrchestratorAction_OrchestratorActionType() {}

func (*OrchestratorAction_TerminateOrchestration) isOrchestratorAction_OrchestratorActionType() {}

type ScheduleTaskAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScheduleTaskAction) Reset() {
	*x = ScheduleTaskAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_v1_actions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleTaskAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskAction) ProtoMessage() {}

func (x *ScheduleTaskAction) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_actions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskAction.ProtoReflect.Descriptor instead.
func (*ScheduleTaskAction) Descriptor() ([]byte, []int) {
	return file_backend_v1_actions_proto_rawDescGZIP(), []int{1}
}

type CreateSubOrchestrationAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateSubOrchestrationAction) Reset() {
	*x = CreateSubOrchestrationAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_v1_actions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSubOrchestrationAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubOrchestrationAction) ProtoMessage() {}

func (x *CreateSubOrchestrationAction) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_actions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubOrchestrationAction.ProtoReflect.Descriptor instead.
func (*CreateSubOrchestrationAction) Descriptor() ([]byte, []int) {
	return file_backend_v1_actions_proto_rawDescGZIP(), []int{2}
}

type CreateTimerAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateTimerAction) Reset() {
	*x = CreateTimerAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_v1_actions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTimerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimerAction) ProtoMessage() {}

func (x *CreateTimerAction) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_actions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimerAction.ProtoReflect.Descriptor instead.
func (*CreateTimerAction) Descriptor() ([]byte, []int) {
	return file_backend_v1_actions_proto_rawDescGZIP(), []int{3}
}

type SendEventAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendEventAction) Reset() {
	*x = SendEventAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_v1_actions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendEventAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEventAction) ProtoMessage() {}

func (x *SendEventAction) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_actions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEventAction.ProtoReflect.Descriptor instead.
func (*SendEventAction) Descriptor() ([]byte, []int) {
	return file_backend_v1_actions_proto_rawDescGZIP(), []int{4}
}

type CompleteOrchestrationAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CompleteOrchestrationAction) Reset() {
	*x = CompleteOrchestrationAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_v1_actions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteOrchestrationAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrchestrationAction) ProtoMessage() {}

func (x *CompleteOrchestrationAction) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_actions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrchestrationAction.ProtoReflect.Descriptor instead.
func (*CompleteOrchestrationAction) Descriptor() ([]byte, []int) {
	return file_backend_v1_actions_proto_rawDescGZIP(), []int{5}
}

type TerminateOrchestrationAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TerminateOrchestrationAction) Reset() {
	*x = TerminateOrchestrationAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_v1_actions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminateOrchestrationAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateOrchestrationAction) ProtoMessage() {}

func (x *TerminateOrchestrationAction) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_actions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateOrchestrationAction.ProtoReflect.Descriptor instead.
func (*TerminateOrchestrationAction) Descriptor() ([]byte, []int) {
	return file_backend_v1_actions_proto_rawDescGZIP(), []int{6}
}

var File_backend_v1_actions_proto protoreflect.FileDescriptor

var file_backend_v1_actions_proto_rawDesc = []byte{
	0x0a, 0x18, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x64, 0x74, 0x6d, 0x62,
	0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc6, 0x05, 0x0a,
	0x12, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x73, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x4a, 0x0a, 0x0d, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64,
	0x74, 0x6d, 0x62, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x69, 0x0a, 0x18, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x75, 0x62, 0x5f,
	0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x64, 0x74, 0x6d, 0x62, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x4f,
	0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x16, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x4f,
	0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x0c,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x74, 0x6d, 0x62, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x74, 0x6d, 0x62,
	0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x73,
	0x65, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x65, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x5f, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x64, 0x74, 0x6d, 0x62, 0x2e,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x15, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x68, 0x0a, 0x17, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x72, 0x63,
	0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2d, 0x2e, 0x64, 0x74, 0x6d, 0x62, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x63, 0x68,
	0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x16, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x63, 0x68,
	0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x1a, 0x0a, 0x18, 0x6f, 0x72, 0x63,
	0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1e, 0x0a, 0x1c, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x13, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x4f,
	0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x1e, 0x0a, 0x1c, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x61, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x64, 0x74, 0x6d, 0x62, 0x2d,
	0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2f, 0x76, 0x31, 0x3b, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0xaa, 0x02, 0x26, 0x4d,
	0x69, 0x63, 0x72, 0x6f, 0x73, 0x6f, 0x66, 0x74, 0x2e, 0x44, 0x54, 0x4d, 0x42, 0x2e, 0x42, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2e, 0x47, 0x72,
	0x70, 0x63, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_v1_actions_proto_rawDescOnce sync.Once
	file_backend_v1_actions_proto_rawDescData = file_backend_v1_actions_proto_rawDesc
)

func file_backend_v1_actions_proto_rawDescGZIP() []byte {
	file_backend_v1_actions_proto_rawDescOnce.Do(func() {
		file_backend_v1_actions_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_v1_actions_proto_rawDescData)
	})
	return file_backend_v1_actions_proto_rawDescData
}

var file_backend_v1_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_backend_v1_actions_proto_goTypes = []interface{}{
	(*OrchestratorAction)(nil),           // 0: dtmb.backend.v1.OrchestratorAction
	(*ScheduleTaskAction)(nil),           // 1: dtmb.backend.v1.ScheduleTaskAction
	(*CreateSubOrchestrationAction)(nil), // 2: dtmb.backend.v1.CreateSubOrchestrationAction
	(*CreateTimerAction)(nil),            // 3: dtmb.backend.v1.CreateTimerAction
	(*SendEventAction)(nil),              // 4: dtmb.backend.v1.SendEventAction
	(*CompleteOrchestrationAction)(nil),  // 5: dtmb.backend.v1.CompleteOrchestrationAction
	(*TerminateOrchestrationAction)(nil), // 6: dtmb.backend.v1.TerminateOrchestrationAction
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
}
var file_backend_v1_actions_proto_depIdxs = []int32{
	7, // 0: dtmb.backend.v1.OrchestratorAction.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: dtmb.backend.v1.OrchestratorAction.schedule_task:type_name -> dtmb.backend.v1.ScheduleTaskAction
	2, // 2: dtmb.backend.v1.OrchestratorAction.create_sub_orchestration:type_name -> dtmb.backend.v1.CreateSubOrchestrationAction
	3, // 3: dtmb.backend.v1.OrchestratorAction.create_timer:type_name -> dtmb.backend.v1.CreateTimerAction
	4, // 4: dtmb.backend.v1.OrchestratorAction.send_event:type_name -> dtmb.backend.v1.SendEventAction
	5, // 5: dtmb.backend.v1.OrchestratorAction.complete_orchestration:type_name -> dtmb.backend.v1.CompleteOrchestrationAction
	6, // 6: dtmb.backend.v1.OrchestratorAction.terminate_orchestration:type_name -> dtmb.backend.v1.TerminateOrchestrationAction
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_backend_v1_actions_proto_init() }
func file_backend_v1_actions_proto_init() {
	if File_backend_v1_actions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backend_v1_actions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestratorAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_v1_actions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleTaskAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_v1_actions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSubOrchestrationAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_v1_actions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTimerAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_v1_actions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendEventAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_v1_actions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteOrchestrationAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_v1_actions_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TerminateOrchestrationAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_backend_v1_actions_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*OrchestratorAction_ScheduleTask)(nil),
		(*OrchestratorAction_CreateSubOrchestration)(nil),
		(*OrchestratorAction_CreateTimer)(nil),
		(*OrchestratorAction_SendEvent)(nil),
		(*OrchestratorAction_CompleteOrchestration)(nil),
		(*OrchestratorAction_TerminateOrchestration)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_v1_actions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backend_v1_actions_proto_goTypes,
		DependencyIndexes: file_backend_v1_actions_proto_depIdxs,
		MessageInfos:      file_backend_v1_actions_proto_msgTypes,
	}.Build()
	File_backend_v1_actions_proto = out.File
	file_backend_v1_actions_proto_rawDesc = nil
	file_backend_v1_actions_proto_goTypes = nil
	file_backend_v1_actions_proto_depIdxs = nil
}
